import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { FavoritesProvider } from '../contexts/FavoriteContext'
import { Inter } from '@next/font/google'
import Head from 'next/head'
import { Layout } from '../components/Layout'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div className={`${inter.variable} font-sans`}>
      <FavoritesProvider>
        <Head>
          <title>Filmica - Discover your favourite films</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </FavoritesProvider>
    </div>
  )
}
